[project]
name = "wf-wifi-forensics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "rich>=14.0.0",
    "uvicorn>=0.35.0",
]

[project.scripts]
wf = "wf.cli:main"
